apiVersion: apps/v1
kind: Deployment
metadata:
  name: mk-simple-autos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mk-simple-autos
  template:
    metadata:
      labels:
        app: mk-simple-autos
    spec:
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: simple-autos-deploy-token
      containers:
        - image: registry.gitlab.galvanize.com/galvanize-it/curricula/delivery/enterprise/sf/cse-caas-november-2023/student-work/murali-venigalla/simple-autos
          name: mk-simple-autos
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: autos-secret
                  key: db-password
                  optional: false
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mk-config
                  key: DB_HOST
                  optional: false
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mk-config
                  key: DB_PORT
                  optional: false
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mk-config
                  key: DB_USER
                  optional: false
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mk-config
                  key: DB_NAME
                  optional: false

           