apiVersion: v1
kind: Service
metadata:
  name: mk-simple-autos
spec:
  type: LoadBalancer
  selector:
    app: mk-simple-autos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http