apiVersion: v1
kind: Service
metadata:
  name: animal-shelter
spec:
  type: LoadBalancer
  selector:
    app: animal-shelter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http