apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  secret-message: V2UgaG9wZSB5b3UgaGF2ZSBlbmpveWVkIGxlYXJuaW5nIGFib3V0IENvbmZpZ01hcHMgYW5kIFNlY3JldHMgaW4gS3ViZXJuZXRlcy4gIFRoYW5rIHlvdSBmb3IgeW91ciB0aW1lCg==