apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-ml-app.fullname" . }}
  labels:
    {{- include "flask-ml-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    {{- include "flask-ml-app.selectorLabels" . | nindent 6 }}
