
build:
  image: 
    name: gcr.io/kaniko-project/executor:v1.15.0-debug
    entrypoint: [""]
  stage: build
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:$CI_PIPELINE_IID"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --cleanup



