apiVersion: v1
kind: Service
metadata:
  name: mk-hello-spring-lb
spec:
  type: LoadBalancer
  selector:
    app: mk-hello-spring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http