apiVersion: v1
kind: Service
metadata:
  name: vk-react-app
  labels:
    app: vk-react-app
spec:
  type: LoadBalancer
  selector:
    app: vk-react-app 
  ports:
    - name: 'http'
      port: 3000
      targetPort: 3000